### ISSUE TITLE
TimeoutError while using the API

### ISSUE THREAD

**Issue by vpanichkin** [mondbaron/mvg#7]
Got an error:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 60] Connect call failed ('188.164.238.26', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mvg/mvgapi.py", line 112, in __api
    async with session.get(url.url, ssl=False) as resp:
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host www.mvg.de:443 ssl:False [Connect call failed ('188.164.238.26', 443)]


Traceback (most recent call last):
    station = MvgApi.station('Universität, München')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mvg/mvgapi.py", line 251, in station
    return asyncio.run(MvgApi.station_async(query))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mvg/mvgapi.py", line 206, in station_async
    result = await MvgApi.__api(Base.FIB, Endpoint.FIB_LOCATION, args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mvg/mvgapi.py", line 122, in __api
    raise MvgApiError(f"Bad API call: Got {str(type(exc))} from {url.url}") from exc
mvg.mvgapi.MvgApiError: Bad API call: Got <class 'aiohttp.client_exceptions.ClientConnectorError'> from https://www.mvg.de/api/fib/v2/location?query=Universit%C3%A4t%2C+M%C3%BCnchen
```

 while running example snippet:

```
from mvg import MvgApi, TransportType

station = MvgApi.station('Universität, München')
if station:
    mvgapi = MvgApi(station['id'])
    departures = mvgapi.departures(
        limit=3,
        offset=5,
        transport_types=[TransportType.UBAHN])
    print(station)
    print("-0---")
    print(departures)
```

Also the curl doesn't work:

```
curl --location 'https://www.mvg.de/api/fib/v2/location?query=Universit%C3%A4t%2C%2BM%C3%BCnchen'
```

**Comment by vpanichkin** [comment]
UPD: the curl above works when skipping SSL check

```
curl -k --location 'https://www.mvg.de/api/fib/v2/location?query=Universit%C3%A4t%2C%2BM%C3%BCnchen'
```

**Comment by vpanichkin** [comment]
It recovered without any input from my side. Closing...
